﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Refit;
using TekConf.Mobile.Core.Dtos;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
    }
}

namespace ResilientServices
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedITekConfApi : ITekConfApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedITekConfApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<List<ConferenceDto>> GetConferences()
        {
            var arguments = new object[] {  };
            return (Task<List<ConferenceDto>>) methodImpls["GetConferences"](Client, arguments);
        }

        public virtual Task<ConferenceDto> GetConference(string slug)
        {
            var arguments = new object[] { slug };
            return (Task<ConferenceDto>) methodImpls["GetConference"](Client, arguments);
        }

    }
}


